# Generated by Django 5.2.6 on 2025-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsejoConsultivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateField()),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        help_text="Documento opcional (PDF, Word, etc.)",
                        null=True,
                        upload_to="consejo_consultivo/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicación del Consejo Consultivo",
                "verbose_name_plural": "Publicaciones del Consejo Consultivo",
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("EVENTO", "Evento"),
                    ("NOTICIA", "Noticia"),
                    ("BLOG", "Blog"),
                    ("CAPACITACION", "Capacitación"),
                ],
                max_length=20,
            ),
        ),
    ]
