# Generated by Django 5.2.6 on 2025-09-25 15:20

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_consejoconsultivo_alter_publicacion_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtractivoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=220,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "como_llegar",
                    models.TextField(
                        help_text="Instrucciones sobre cómo llegar al atractivo."
                    ),
                ),
                (
                    "ubicacion_mapa",
                    models.CharField(
                        blank=True,
                        help_text="Coordenadas (lat,lng) para Google Maps",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "categoria_color",
                    models.CharField(
                        choices=[
                            ("AMARILLO", "Cultural/Histórico"),
                            ("ROJO", "Urbano/Parque"),
                            ("BLANCO", "Natural"),
                        ],
                        max_length=10,
                        verbose_name="Categoría de Color",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Funcionario o Administrador que creó el registro.",
                        limit_choices_to={"role__in": ["ADMIN", "FUNCIONARIO"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Atractivo Turístico",
                "verbose_name_plural": "Atractivos Turísticos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenAtractivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to=api.models.atractivo_directory_path),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad y SEO",
                        max_length=255,
                    ),
                ),
                (
                    "atractivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="api.atractivoturistico",
                    ),
                ),
            ],
        ),
    ]
