# Generated by Django 5.2.6 on 2025-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_atractivoturistico_imagenatractivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacion",
            name="subcategoria_evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FESTIVAL_PRINCIPAL", "Festival o Evento Principal"),
                    ("CELEBRACION_LLANERIDAD", "Celebración de la Llaneridad"),
                    ("ACTIVIDAD_CIVICA", "Actividad Cultural o Cívica"),
                    ("OTRO", "Otro"),
                ],
                help_text="Clasificación específica solo para eventos.",
                max_length=50,
                null=True,
                verbose_name="Subcategoría de Evento",
            ),
        ),
    ]
