# Generated by Django 5.2.6 on 2025-09-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_publicacion_subcategoria_evento"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="atractivoturistico",
            name="es_publicado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para que el atractivo sea visible en el sitio web público.",
                verbose_name="Publicado",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador General"),
                    ("FUNCIONARIO", "Funcionario de Turismo"),
                    ("PRESTADOR", "Prestador de Servicio"),
                    ("TURISTA", "Turista"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
        migrations.CreateModel(
            name="ElementoGuardado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("fecha_guardado", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        limit_choices_to={"role": "TURISTA"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos_guardados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_guardado"],
                "unique_together": {("usuario", "content_type", "object_id")},
            },
        ),
    ]
