# Generated by Django 5.2.6 on 2025-09-25 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_atractivoturistico_es_publicado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContenidoMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        choices=[
                            ("INTRODUCCION", "Introducción General"),
                            ("UBICACION_CLIMA", "Ubicación y Clima"),
                            ("ALOJAMIENTO", "Alojamiento y Hotelería"),
                            ("COMO_LLEGAR", "¿Cómo Llegar?"),
                            ("CONTACTOS", "Contactos de Interés"),
                            ("FINANZAS", "Entidades Financieras"),
                            ("OTRA", "Otra Sección"),
                        ],
                        help_text="Agrupa el contenido bajo una categoría temática.",
                        max_length=50,
                        verbose_name="Sección Temática",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="El título principal que se mostrará para este bloque de contenido.",
                        max_length=255,
                        verbose_name="Título del Bloque",
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="El contenido principal. Se recomienda usar formato Markdown para el texto.",
                        verbose_name="Contenido del Bloque",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Define el orden de aparición de los bloques en la página (0 primero, 1 después, etc.).",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Último usuario que modificó este contenido.",
                        limit_choices_to={"role__in": ["ADMIN", "FUNCIONARIO"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido del Municipio",
                "verbose_name_plural": "Contenidos del Municipio",
                "ordering": ["orden", "titulo"],
            },
        ),
    ]
