# Generated by Django 5.2.6 on 2025-09-25 22:51

from django.db import migrations
from django.utils.translation import gettext_lazy as _

def poblar_contenido_secretaria(apps, schema_editor):
    """
    Puebla la base de datos con el contenido inicial sobre la Secretaría de Turismo.
    """
    ContenidoMunicipio = apps.get_model('api', 'ContenidoMunicipio')

    # Usamos .update_or_create para evitar duplicados si la migración se ejecuta más de una vez.
    # El 'titulo' se usará como identificador único para cada bloque.
    ContenidoMunicipio.objects.update_or_create(
        titulo="Creación y Misión de la Secretaría de Turismo",
        defaults={
            'seccion': 'SECRETARIA_TURISMO',
            'contenido': _(
                "La Secretaría de Turismo y Desarrollo Económico de Puerto Gaitán fue creada con el objetivo de "
                "impulsar el crecimiento sostenible del municipio, diversificando su economía más allá de la "
                "industria petrolera. Su misión es posicionar a Puerto Gaitán como un destino turístico de "
                "referencia en los Llanos Orientales, destacando su riqueza natural, cultural y étnica. "
                "La secretaría trabaja en colaboración con las comunidades locales, prestadores de servicios y "
                "el gobierno para desarrollar productos turísticos auténticos y de alta calidad que beneficien "
                "a toda la población."
            ),
            'orden': 0
        }
    )

    ContenidoMunicipio.objects.update_or_create(
        titulo="Funciones de la Secretaría de Turismo",
        defaults={
            'seccion': 'SECRETARIA_TURISMO',
            'contenido': _(
                "Las funciones principales de la secretaría incluyen:\n"
                "- Planificar y ejecutar políticas y proyectos para el fomento del turismo.\n"
                "- Promocionar los atractivos turísticos del municipio a nivel nacional e internacional.\n"
                "- Ofrecer capacitación y apoyo a los prestadores de servicios turísticos locales.\n"
                "- Fomentar el ecoturismo y las prácticas de turismo sostenible para preservar el patrimonio natural.\n"
                "- Apoyar y visibilizar las iniciativas culturales y artesanales de las comunidades indígenas y campesinas.\n"
                "- Gestionar la infraestructura turística y mejorar la experiencia del visitante."
            ),
            'orden': 1
        }
    )

    ContenidoMunicipio.objects.update_or_create(
        titulo="Dirección de Turismo",
        defaults={
            'seccion': 'SECRETARIA_TURISMO',
            'contenido': _(
                "La Dirección de Turismo es el brazo ejecutor de la Secretaría. Es responsable de la "
                "operación diaria de los programas turísticos, la atención directa a los visitantes y "
                "prestadores de servicios, y la organización de eventos y actividades que dinamicen el "
                "sector. Trabaja en estrecha colaboración con el Consejo Consultivo de Turismo para asegurar "
                "que las estrategias implementadas respondan a las necesidades y oportunidades del municipio, "
                "garantizando un desarrollo turístico inclusivo y sostenible."
            ),
            'orden': 2
        }
    )

def unpoblar_contenido(apps, schema_editor):
    """
    Elimina el contenido creado si la migración se revierte.
    """
    ContenidoMunicipio = apps.get_model('api', 'ContenidoMunicipio')
    ContenidoMunicipio.objects.filter(
        seccion='SECRETARIA_TURISMO',
        titulo__in=[
            "Creación y Misión de la Secretaría de Turismo",
            "Funciones de la Secretaría de Turismo",
            "Dirección de Turismo"
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_contenidomunicipio_seccion"),
    ]

    operations = [
        migrations.RunPython(poblar_contenido_secretaria, unpoblar_contenido),
    ]